config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  get 'new' => 'posts#new'

  resources :pages
  resources :posts

  # namespace :users do
  #   resources :sessions, only: [:create, :destroy]
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  apipie
  namespace :api do
    namespace :v1 do
      post "users/register"
      post "users/login"
      post "users/logout"
      post "users/forgot_password"
      post "users/resend_confirmation"
      post "users/update"
      post "users/update_password"
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord

	belongs_to :user

  validates :title, presence: true,
                    length: {minimum: 5}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)

    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private def post_params
    params.require(:post).permit(:title, :body, :img, :date)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <h3 class="display-4">Edit Post</h3>
    <p class="lead">
      <%= form_for :post, url: post_path(@post), method: :patch do |f| %>
        <% if @post.errors.any? %>
          <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
            <% end %>
        <% end %>

        <p>
          <%= f.label :title %>
          <%= f.text_field(:title, {:class => 'form-control'}) %>
        </p>

        <p>
          <%= f.label :body %>
          <%= f.text_area(:body, {:class => 'form-control'}) %>
        </p>

        <p>
          <%= f.submit({:class => 'btn btn-primary'}) %>
        </p>
      <% end %>
    </p>
  </div>
  </div>
</div>
</main><!-- /.container -->

app/views/posts/index.html.erb
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
  <div class="col-md-12 p-lg-5 mx-auto my-5">
    <h1 class="display-4 font-weight-normal">Welcome to Quartz Forum</h1>
    <p class="lead font-weight-normal">Contola Sasingatura Saprawala</p>
      <a class="btn btn-outline-secondary" <%= link_to "More", about_path %></a>
  </div>
  <div class="product-device shadow-sm d-none d-md-block"></div>
  <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
</div>
<br><br>
<% if user_signed_in? %>
<div class="row mb-2">
  <% @posts.each do |post| %>
     <div class="col-md-6">
       <div class="card flex-md-row mb-4 shadow-sm h-md-250">
         <div class="card-body d-flex flex-column align-items-start">
           <h3 class="mb-0">
             <a class="text-dark" href="#"><%= post.title%></a>
           </h3>
           <div class="mb-1 text-muted"><%= post.date %></div>
           <p class="card-text mb-auto"><%= post.body %></p>
           <%= link_to "Read More", post_path(post) %>
         </div>
         <%= image_tag post.img, class: 'image-post' %>
       </div>
   </div>
   <% end %>
 </div>
 <% end %>

app/views/posts/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h3 class="display-4">Add Post</h3>
    <p class="lead">
      <%= simple_form_for :post, url: posts_path do |f| %>
        <% if @post.errors.any? %>
          <% @post.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
            <% end %>
        <% end %>

        <p>
          <%= f.input :title, {:class => 'form-control', maxlength: 10}  %>
        </p>

        <p>
          <%= f.label :body %>
          <%= f.text_area(:body, {:class => 'form-control', maxlength: 150}) %>
        </p>

        <p>
          <%= f.submit({:class => 'btn btn-primary'}) %>
        </p>
      <% end %>
    </p>
  </div>
  </div>
</div>
</main><!-- /.container -->

app/views/posts/show.html.erb
<div class="jumbotron">
  <div class="container">
    <h3 class="display-4"><%= @post.title %></h3>
    <p class="lead">

      <p><%= @post.body %></p>
    <hr>
      <%=  link_to "Edit", edit_post_path(@post), :class => 'btn
            btn-default' %>
      <%=  link_to "Delete", post_path(@post),
                            method: :delete,
                            data: {confirm: 'Are you sure?'},
                            :class => 'btn btn-default' %>
    </p>
  </div>
  </div>
</div>
</main><!-- /.container -->