config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }
  root 'posts#index', as: 'home'
  get 'about' => 'pages#about', as: 'about'
  get 'new' => 'posts#new'

  resources :pages
  resources :posts

  # namespace :users do
  #   resources :sessions, only: [:create, :destroy]
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  apipie
  namespace :api do
    namespace :v1 do
      post "users/register"
      post "users/login"
      post "users/logout"
      post "users/forgot_password"
      post "users/resend_confirmation"
      post "users/update"
      post "users/update_password"
    end
  end

end

app/views/layouts/_login.html.erb
<div class="login">
  <div class="login-header">
    <h3>Member Sign In</h3>
  </div>
    <hr>

    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
      </div>
    <br>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, autocomplete: "current-password" %>
      </div>

      <% if devise_mapping.rememberable? -%>
        <label class="form-check-label" style="margin-left: 20px;">
          <%= f.check_box :remember_me, class: "form-check-input" %>
          <%= f.label :remember_me, style: "padding-bottom: .15rem" %>
        </label>
      <% end -%>

      <div class="actions">
            <%= button_tag type: 'submit', :class => "btn btn-light btn-outline-secondary btn-md" do %>
                  <i class="fa fa-sign-in"></i>
           <% end %>
    <% end %>


        </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quartz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('qz.jpg') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

 <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="#"><%= image_tag("qz.jpg", :class => "header-img") %></a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="#"><h2 style="font-family:
                    courier new;">TheQuartz Gallery</h2></a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            <a class="text-muted" href="#">
              <svg xmlns="search.png" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mx-3">
                  <circle cx="10.5" cy="10.5" r="7.5"></circle><line x1="21" y1="21" x2="15.8" y2="15.8"></line></svg>
            </a>
              <% if user_signed_in? %>
                  <a class="btn btn-sm btn-outline-danger" <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></a>
              <% else %>
              <div class="dropdown">
                <a href="#" class="btn btn-sm btn-outline-secondary" data-toggle="dropdown">Member<span class="caret"></span></a>
                  <ul id="login-dp" class="dropdown-menu">
                    <li>
                      <%= render 'layouts/login' %>
                    </li>
                  </ul>
                </div>
          <% end %>
          </div>
        </div>
      </header>
<hr>
      <div class="nav-scroller py-1 mb-2">
        <nav class="nav d-flex">
          <a class="p-2 text-muted" <%= link_to "Home", home_path %></a>
          <a class="p-2 text-muted" <%= link_to "About", about_path %></a>
          <% if user_signed_in? %>
            <a class="p-2 text-muted" <%= link_to "Create Post", new_post_path %></a>
            <a class="p-2 text-muted" <%= link_to "Gallery", galleries_path %></a>
            <a class="p-2 text-muted" <%= link_to "Calendar", events_path %></a>
          <% end %>
        </nav>
      </div>

    <hr><hr><br>
    <%= yield %>
    <br><br><br><hr><hr><br>
      <footer class="footer">
          <div class="container">
          <%= link_to 'Download', download_download_url %>
          <span class="text-muted">&copy; TheQuartz 2016-2018</span>
        </div>
        </footer>
  </body>
</html>